## Built with Hugo 0.74.3 extended

baseURL = "https://pghbridge.github.io/web/"
title = "Pittsburgh Bridge"

languageCode = "en-us"
publishDir = "docs"

hasCJKLanguage = true
metaDataFormat = "yaml"

[params]
    description = "Spanning Kink Communities"
